// Example mock data for testing
// Import this in your page.jsx to use mock data during development

export const mockMaterialData = {
  id: "1",
  name: "Carrara White Marble Tile - 12x24",
  category: "Carrara Marble",
  categoryId: "marble-tiles",
  size: "12x24 inches",
  pricePerSqFt: 8.5,
  boxSize: 10, // sq ft per box
  boxSizeImperial: "900 BF / box",
  rating: 4.8,
  reviewCount: 42,
  inStock: true,
  ratingDistribution: {
    5: 78,
    4: 15,
    3: 5,
    2: 2,
    1: 0,
  },
  images: ["/mock/1.svg", "/mock/2.svg", "/mock/3.svg", "/mock/4.svg"],
  description:
    "Elevate your space with the timeless elegance of Carrara White Marble. Sourced directly from Italy, each 12x24 tile features a pristine white background with subtle grey veining. Perfect for bathroom floors, kitchen backsplashes, or statement walls.",
  material: "Natural Marble",
  finish: "Polished",
  thickness: "10mm",
  edgeType: "Rectified",
  application: "Floor & Wall",
  origin: "Italy",
  features: [
    "Genuine Italian Carrara Marble",
    "Polished finish for a high-gloss reflection",
    "Rectified edges for minimal grout lines",
    "Suitable for residential and commercial tramock/1.svg",
  ],
};

export const mockSimilarMaterials = [
  {
    id: "2",
    name: "Calacatta Gold 12x24",
    subtitle: "Italian Marble",
    price: 12.5,
    image: "/mock/1.svg",
    rating: 4.9,
    inStock: true,
  },
  {
    id: "3",
    name: "Statuary White 12x24",
    subtitle: "Premium Porcelain",
    price: 6.99,
    image: "/mock/2.svg",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "4",
    name: "Emperador Dark 12x24",
    subtitle: "Spanish Marble",
    price: 9.25,
    image: "/mock/3.svg",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "5",
    name: "Travertine Beige 12x24",
    subtitle: "Natural Stone",
    price: 5.5,
    image: "/mock/1.svg",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "6",
    name: "Nero Marquina 12x24",
    subtitle: "Spanish Marble",
    price: 11.75,
    image: "/mock/2.svg",
    rating: 4.8,
    inStock: false,
  },
  {
    id: "7",
    name: "Thassos White 12x24",
    subtitle: "Greek Marble",
    price: 15.99,
    image: "/mock/3.svg",
    rating: 5.0,
    inStock: true,
  },
  {
    id: "8",
    name: "Crema Marfil 12x24",
    subtitle: "Spanish Marble",
    price: 7.25,
    image: "/mock/1.svg",
    rating: 4.4,
    inStock: true,
  },
  {
    id: "9",
    name: "Carrara Bianco 12x24",
    subtitle: "Italian Marble",
    price: 8.99,
    image: "/mock/2.svg",
    rating: 4.7,
    inStock: true,
  },
];
